apiVersion: v1 # Specifies the API version used for the PVC resource.
kind: PersistentVolumeClaim # Specifies the type of Kubernetes resource being defined.
metadata:
    name: mssql-claim # Gives the PVC a unique name within the namespace.
spec: 
    accessModes:
    - ReadWriteMany # Allows multiple pods to read from and write to this volume simultaneously.
    resources:
        requests:
            storage: 200Mi # Requests 200 MiB of storage space for this PVC.
